### ISSUE TITLE
Get download working for full stompy arm. 

### ISSUE THREAD

**Issue by wuallenwu** [kscalelabs/onshape#28]
Currently, running `kol urdf https://cad.onshape.com/documents/afaee604f6ca311526a6aec8/w/29af84cb974c2d825b71de39/e/949e5b6cd071fee000e2c296` raises the following error:

```
WARNING 2024-06-12 17:25:52 [kol.onshape.converter] Cache invalidated after 1 minutes
  INFO  2024-06-12 17:25:52 [kol.onshape.converter] Downloading file /Users/allen/KScale/onshape/robot/meshes/upper_left_arm_1_arm_part_6_1.stl
  INFO  2024-06-12 17:25:55 [kol.onshape.converter] Converting STL file to /Users/allen/KScale/onshape/robot/meshes/upper_left_arm_1_arm_part_6_1.stl
Traceback (most recent call last):
  File "/Users/allen/anaconda3/envs/kol/bin/kol", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/allen/KScale/onshape/kol/scripts/cli.py", line 29, in main
    get_urdf.main(remaining_args)
  File "/Users/allen/KScale/onshape/kol/scripts/get_urdf.py", line 70, in main
    ).save_urdf()
      ^^^^^^^^^^^
  File "/Users/allen/KScale/onshape/kol/onshape/converter.py", line 863, in save_urdf
    urdf_joint = self.get_urdf_joint(joint)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/KScale/onshape/kol/onshape/converter.py", line 725, in get_urdf_joint
    joint_limits = self.joint_limits[joint_info_key]
                   ^^^^^^^^^^^^^^^^^
  File "/Users/allen/anaconda3/envs/kol/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/KScale/onshape/kol/onshape/converter.py", line 549, in joint_limits
    **{
      ^
  File "/Users/allen/KScale/onshape/kol/onshape/converter.py", line 550, in <dictcomp>
    sub_assembly.key: download_or_get_cached_features(sub_assembly)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/KScale/onshape/kol/onshape/converter.py", line 539, in download_or_get_cached_features
    return self.get_or_use_cached(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/KScale/onshape/kol/onshape/converter.py", line 181, in get_or_use_cached
    item = get_fn()
           ^^^^^^^^
  File "/Users/allen/KScale/onshape/kol/onshape/converter.py", line 541, in <lambda>
    lambda: self.api.get_features(assembly),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/KScale/onshape/kol/onshape/api.py", line 76, in get_features
    return Features.model_validate(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/allen/anaconda3/envs/kol/lib/python3.11/site-packages/pydantic/main.py", line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Features
featureStates.5.value.message.featureStatus
  Input should be 'OK' [type=enum, input_value='ERROR', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/enum'.
```

A current quick fix is to add ERROR to the featurestatus, but that is probably not the best idea long term
`class FeatureStatus(str, Enum):
    OK = "OK"
    ERROR = "ERROR"`

**Comment by budzianowski** [comment]
The error status of the part does not invalidate the build fully. We can add the ERROR to the feature status like here: https://github.com/kscalelabs/onshape/pull/33
