### ISSUE TITLE
Issue running kol command for MicroStompy in python 3.12.4

### ISSUE THREAD

**Issue by KelLynnP** [kscalelabs/onshape#96]
(base) kelseypool@MacBook-Pro-3 randbox % kol run \                                     
  'https://cad.onshape.com/documents/cacc96f8a7850b951e7aa69a/w/3a0a4ee9d8251956ba5e5e92/e/d466d644261b5146fb5a1714' \
  default_part_mass=0.01 \
  'default_revolute_joint_limits=[0, 3.14159]' \
  default_revolute_joint_effort=1.5 \
    default_revolute_joint_velocity=5.51
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/kol", line 5, in <module>
    from kol.scripts.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/kol/scripts/cli.py", line 6, in <module>
    from kol.scripts import get_mjcf, get_urdf, pybullet, show_mjcf, visualize_stl
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/kol/scripts/get_mjcf.py", line 9, in <module>
    from kol.onshape.converter import Converter
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/kol/onshape/converter.py", line 23, in <module>
    from kol.onshape.api import OnshapeApi
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/kol/onshape/api.py", line 7, in <module>
    from kol.onshape.schema.assembly import Assembly, AssemblyMetadata, Part, RootAssembly, SubAssembly
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/kol/onshape/schema/assembly.py", line 225, in <module>
    class AssemblyMetadata(BaseModel):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/main.py", line 221, in __new__
    inferred = ModelField.infer(
               ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/fields.py", line 504, in infer
    return cls(
           ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/fields.py", line 434, in __init__
    self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/fields.py", line 555, in prepare
    self.populate_validators()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/fields.py", line 829, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/validators.py", line 765, in find_validators
    raise RuntimeError(f'no validator found for {type_}, see `arbitrary_types_allowed` in Config')
RuntimeError: no validator found for <class 'functools.cached_property'>, see `arbitrary_types_allowed` in Config

**Comment by codekansas** [comment]
Fixed this in person! Turns out it was because `kscale-onshape-library` was installed in the base Conda environment, which used Python 3.12, which was not supported. You can verify using

```bash
which kol
```

to see that the CLI points to the one in the base environment. To fix this, instead do:

```bash
pip uninstall kscale-onshape-library  # From the base environment
conda create --name onshape python=3.11  # Currently, this is the only tested Python version
conda activate onshape
pip install 'kscale-onshape-library[all]'
```
