### ISSUE TITLE
Support for Composite parts 

### ISSUE THREAD

**Issue by KelLynnP** [kscalelabs/onshape#99]
Example here:

🟥 Assy w/ Composite Parts:
https://cad.onshape.com/documents/cacc96f8a7850b951e7aa69a/v/0b68bc480ee9159c974e6336/e/a3debca6b790e5cda599c3ae

🟥  Assy w/ Composite Parts:
https://cad.onshape.com/documents/cacc96f8a7850b951e7aa69a/v/0b68bc480ee9159c974e6336/e/d49d00bd4f2b6590cdfcf001

✅ Assy w/ Non Composite Parts:
https://cad.onshape.com/documents/cacc96f8a7850b951e7aa69a/v/0b68bc480ee9159c974e6336/e/6b28234cd16e8c5c8316bbbf

Full error:
  INFO  2024-10-05 16:45:11 [httpx] HTTP Request: GET https://cad.onshape.com/api/assemblies/d/cacc96f8a7850b951e7aa69a/v/0b68bc480ee9159c974e6336/e/a3debca6b790e5cda599c3ae?includeMateFeatures=true&includeMateConnectors=true&includeNonSolids=true&configuration=default "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/kol/onshape/download.py", line 713, in check_document
    assembly = await api.get_assembly(document_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/kol/onshape/cached_api.py", line 74, in get_assembly
    return await self.cacher(
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/kol/onshape/cacher.py", line 65, in __call__
    item = await get_fn()
           ^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/kol/onshape/api.py", line 115, in get_assembly
    return Assembly.model_validate(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/pydantic/main.py", line 593, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Assembly
parts.0.bodyType
  Input should be 'solid' [type=enum, input_value='composite', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/enum

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/onshape/bin/kol", line 8, in <module>
    sys.exit(sync_main())
             ^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/kol/scripts/cli.py", line 39, in sync_main
    asyncio.run(main())
  File "/opt/miniconda3/envs/onshape/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/kol/scripts/cli.py", line 27, in main
    await download_and_postprocess_main(remaining_args)
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/kol/onshape/postprocess.py", line 102, in download_and_postprocess_main
    document_info = await download(
                    ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/kol/onshape/download.py", line 1306, in download
    checked_document = await check_document(document, api, config=config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/onshape/lib/python3.11/site-packages/kol/onshape/download.py", line 715, in check_document
    raise FailedCheckError(
kol.onshape.download.FailedCheckError: Failed to get assembly for document https://cad.onshape.com/documents/cacc96f8a7850b951e7aa69a/v/0b68bc480ee9159c974e6336/e/a3debca6b790e5cda599c3ae

Suggestions:
 * Check that the document is an assembly, not a part studio.

Original error:
1 validation error for Assembly
parts.0.bodyType
  Input should be 'solid' [type=enum, input_value='composite', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/enum

**Comment by hezretaly** [comment]
Hey Kelsey, does it have to produce a robot.urdf file (with robot.tgz, and .cache, meshes folders) in a folder of choice or are there any requirements other than that? i ran the `onshape run ...` command and it successfully converted both https://cad.onshape.com/documents/cacc96f8a7850b951e7aa69a/v/0b68bc480ee9159c974e6336/e/a3debca6b790e5cda599c3ae & https://cad.onshape.com/documents/cacc96f8a7850b951e7aa69a/v/0b68bc480ee9159c974e6336/e/d49d00bd4f2b6590cdfcf001. for example here's the urdf file for [Composite LX-16](https://cad.onshape.com/documents/cacc96f8a7850b951e7aa69a/v/0b68bc480ee9159c974e6336/e/d49d00bd4f2b6590cdfcf001) model
```xml
<?xml version="1.0" ?>
<robot name="composite_lx-16">
  <link name="base">
    <visual name="base_visual">
      <geometry name="base_geometry">
        <sphere radius="0.01"/>
      </geometry>
      <material name="base_material">
        <color rgba="1 0 0 1"/>
      </material>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <inertial name="base_inertial">
      <mass value="0.001"/>
      <inertia ixx="0.000001" iyy="0.000001" izz="0.000001" ixy="0" ixz="0" iyz="0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </link>
  <joint name="base_joint" type="fixed">
    <parent link="base"/>
    <child link="LX_16A"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  <joint name="Revolute_1" type="revolute">
    <origin xyz="0 -0.022549 0.000034" rpy="-1.570796 -1.570796 0"/>
    <parent link="LX_16A"/>
    <child link="LX_16A_2"/>
    <limit effort="80" velocity="5" lower="-1.570796" upper="1.570796"/>
    <axis xyz="0 0 1"/>
  </joint>
  <joint name="Revolute_2" type="revolute">
    <origin xyz="0 0.012751 -0.019294" rpy="3.141593 0 0"/>
    <parent link="LX_16A"/>
    <child link="LX_16A_3"/>
    <limit effort="80" velocity="5" lower="-1.570796" upper="1.570796"/>
    <axis xyz="0 0 -1"/>
  </joint>
  <joint name="Revolute_3" type="revolute">
    <origin xyz="0 0.012751 0.018706" rpy="0 0 0"/>
    <parent link="LX_16A"/>
    <child link="LX_16A_4"/>
    <limit effort="80" velocity="5" lower="-1.570796" upper="1.570796"/>
    <axis xyz="0 0 -1"/>
  </joint>
  <link name="LX_16A">
    <visual name="LX_16A_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="LX_16A_geometry">
        <mesh filename="meshes/LX_16A.stl"/>
      </geometry>
      <material name="LX_16A_material">
        <color rgba="0.917647 0.917647 0.917647 1"/>
      </material>
    </visual>
    <collision name="LX_16A.collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="LX_16A_collision_geometry">
        <mesh filename="meshes/LX_16A.stl"/>
      </geometry>
    </collision>
    <inertial name="LX_16A_inertial">
      <mass value="0.053848"/>
      <inertia ixx="0.000015" iyy="0.000008" izz="0.000012" ixy="0" ixz="0" iyz="0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </link>
  <link name="LX_16A_2">
    <visual name="LX_16A_visual_2">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="LX_16A_geometry_2">
        <mesh filename="meshes/LX_16A_2.stl"/>
      </geometry>
      <material name="LX_16A_material_2">
        <color rgba="0.917647 0.917647 0.917647 1"/>
      </material>
    </visual>
    <collision name="LX_16A.collision_2">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="LX_16A_collision_geometry_2">
        <mesh filename="meshes/LX_16A_2.stl"/>
      </geometry>
    </collision>
    <inertial name="LX_16A_inertial_2">
      <mass value="0.053848"/>
      <inertia ixx="0.000015" iyy="0.000008" izz="0.000012" ixy="0" ixz="0" iyz="0"/>
      <origin xyz="0 -0.012751 -0.018706" rpy="0 0 0"/>
    </inertial>
  </link>
  <link name="LX_16A_3">
    <visual name="LX_16A_visual_3">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="LX_16A_geometry_3">
        <mesh filename="meshes/LX_16A_3.stl"/>
      </geometry>
      <material name="LX_16A_material_3">
        <color rgba="0.917647 0.917647 0.917647 1"/>
      </material>
    </visual>
    <collision name="LX_16A.collision_3">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="LX_16A_collision_geometry_3">
        <mesh filename="meshes/LX_16A_3.stl"/>
      </geometry>
    </collision>
    <inertial name="LX_16A_inertial_3">
      <mass value="0.053848"/>
      <inertia ixx="0.000008" iyy="0.000015" izz="0.000012" ixy="0" ixz="0" iyz="0"/>
      <origin xyz="-0.012751 0 0.019294" rpy="0 0 0"/>
    </inertial>
  </link>
  <link name="LX_16A_4">
    <visual name="LX_16A_visual_4">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="LX_16A_geometry_4">
        <mesh filename="meshes/LX_16A_4.stl"/>
      </geometry>
      <material name="LX_16A_material_4">
        <color rgba="0.917647 0.917647 0.917647 1"/>
      </material>
    </visual>
    <collision name="LX_16A.collision_4">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry name="LX_16A_collision_geometry_4">
        <mesh filename="meshes/LX_16A_4.stl"/>
      </geometry>
    </collision>
    <inertial name="LX_16A_inertial_4">
      <mass value="0.053848"/>
      <inertia ixx="0.000008" iyy="0.000015" izz="0.000012" ixy="0" ixz="0" iyz="0"/>
      <origin xyz="-0.012751 0 0.019294" rpy="0 0 0"/>
    </inertial>
  </link>
</robot>
```
